import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="emerald" lang="en">
      <body className={inter.className}>
        <main className="m-10 flex flex-col justify-center">
          <Nav />
          {children}
        </main>
      </body>
    </html>
  );
}
